name: docker publish

on:
  # allow manually run the action:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Make package
        run: | 
          git clone https://github.com/apache/iotdb.git
          cd iotdb
          git checkout v1.3.2
          echo 'docker/src/main/DockerCompose/Dockerfile-1.0.0-datanode' >> .gitignore
          cd docker/src/main/DockerCompose
          sed -i 's/  && mv \${target} iotdb/# \&\& mv \${target} iotdb/' docker/src/main/Dockerfile-1.0.0-datanode
          sed -i 's/#  \&\& mv apache-iotdb-\${version}-server-bin iotdb/  \&\& mv apache-iotdb-\${version}-server-bin iotdb/' docker/src/main/Dockerfile-1.0.0-datanode
          cat Dockerfile-1.0.0-datanode
          ./do-docker-build.sh -t all -v 1.3.2 -c aa0ff4adf2fe00368b2145dd5f561d30df06a885 -b -p
          

