name: docker build test

on:
  # allow manually run the action:
  workflow_dispatch:


jobs:

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make package
        run: | 
          git clone https://github.com/apache/iotdb.git;
          cd iotdb/docker/src/main/DockerCompose
          ./do-docker-build.sh -t all -v 1.3.2 -c aa0ff4adf2fe00368b2145dd5f561d30df06a885
          

