name: docker build test

on:
  # allow manually run the action:
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Make package
        run: | 
          git clone https://github.com/apache/iotdb.git
          cd iotdb
          git checkout v1.3.2
          mvn clean package -pl distribution -am -DskipTests
          cd docker/src/main/DockerCompose
          ./do-docker-build.sh -t all -v 1.3.2 -c aa0ff4adf2fe00368b2145dd5f561d30df06a885
          

